export enum CategorieReclamation {
  SUPPORT_ET_ACCOMPAGNEMENT = 'SUPPORT_ET_ACCOMPAGNEMENT',
  FINANCEMENT_ET_OPPORTUNITES = 'FINANCEMENT_ET_OPPORTUNITES',
  RELATIONS_ET_PARTENARIATS = 'RELATIONS_ET_PARTENARIATS',
  ADMINISTRATION_ET_SERVICE_CLIENT = 'ADMINISTRATION_ET_SERVICE_CLIENT'
}


